### ISSUE TITLE
Consider providing instructions on how to get/create the add-on

### ISSUE THREAD

**Issue by jwatt** [mozilla/code-coverage#1028]
It would be helpful if the docs had some information on where to get the add-on from (or else note that there is no such place, currently) and how to build and install the add-on. There's nothing on:

https://github.com/mozilla/code-coverage/blob/master/README.md
https://github.com/mozilla/code-coverage/blob/master/addon/README.md

**Comment by marco-c** [comment]
I've added a link to https://addons.mozilla.org/it/firefox/addon/gecko-code-coverage/ in both READMEs.

**Comment by marco-c** [comment]
Err, https://addons.mozilla.org/firefox/addon/gecko-code-coverage/.

**Comment by jwatt** [comment]
Ah, so I was aware of that AMO page, but it says the add-on's last updated was over two years ago and its 'Homepage' link links to https://github.com/mozilla/code-coverage-addon , which was archived around the same time. There have been a significant number of updates to the copy of the add-on in **this** repo since then, so I assumed the copy in this repo must be published elsewhere.

Can you update the 'Homepage' link on that AMO page to link to this repository (presumably https://github.com/mozilla/code-coverage/blob/master/addon/README.md)? And is there any prospect of the published add-on getting an update any time soon?

**Comment by marco-c** [comment]
> Can you update the 'Homepage' link on that AMO page to link to this repository (presumably https://github.com/mozilla/code-coverage/blob/master/addon/README.md)?

Done!

> And is there any prospect of the published add-on getting an update any time soon?

I will update it. I don't know if it still works to be honest, but I hope so :)

**Comment by marco-c** [comment]
I think it doesn't work anymore :(

I've filed https://github.com/mozilla/code-coverage/issues/1039.

Unfortunately I won't have time to investigate this anytime soon.

**Comment by jwatt** [comment]
That's a shame. Thanks for updating the link and checking whether things still work though. :-)

**Comment by marco-c** [comment]
At least Searchfox integration is now built-in :)
And similarly with Phabricator (but only on the `after` part of the patches, and only after they land in m-c).
