### ISSUE TITLE
Upload sub-reports

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#104]
We are currently retrieving all coverage artifacts, parsing them all together and outputting a overall report.
In order to support #3, we need to upload a separate coverage report for each test suite.

There are a few things to figure out:
1) What is a test suite exactly? I would ignore "non-e10s" and "e10s" variations, I would consider all chunks to be part of the test suite.
2) It is sub-optimal to generate a sub-report for each suite and then re-parse the coverage artifacts to generate the full report. It might be worth adding support to grcov for this, so we parse artifacts only once and generate multiple outputs.
3) Do we generate the full report on the bot and upload it to gcp, or do we generate it on the backend on-the-fly when necessary?

At first we'll only have X sub-reports for X test suites and 1 overall report. We need to consider that we might add more filters (e.g. OS) in the future, so the possible combinations will be many.

Note: if we see that having sub-reports takes too much space, we could also just generate summary reports (that is, file-level information rather than line-level). At the moment I can see any use case where line-level information would be needed for the sub-reports.

**Comment by La0** [comment]
@marco-c Done ?

**Comment by marco-c** [comment]
Yep. Just file an issue for the optimization 2 (generating multiple reports with a single pass, rather than reparsing the files multiple times).
