### ISSUE TITLE
Use tenacity (or similar) instead of re-implementing a retry function

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#110]
We are currently implementing https://github.com/mozilla/code-coverage/blob/10285fb2340ca69343503b9b42cffebd878f2bae/bot/code_coverage_bot/utils.py#L20 and using it in a few places.
We should instead use a library (e.g. tenacity) and remove this custom `retry` function.

**Comment by nicolaslazo** [comment]
Ok, I'll give this a try! I'll try using Tenacity

**Comment by Patil2099** [comment]
@marco-c  Can I work on this?

**Comment by La0** [comment]
@Patil2099 Sure ! You can submit a Pull Request on that repo to replace every `from code_coverage_bot.utils import retry` imports and usage in the `bot` project by a similar [tenacity](https://github.com/jd/tenacity) call.
At the end of your work, you should be able to remove safely our `retry` function as it should not be used anymore.

**Comment by KaairaGupta** [comment]
I want to work on this if it is still an issue? Can i?

**Comment by marco-c** [comment]
Sure, feel free!
