### ISSUE TITLE
All Icons are not loading

### ISSUE THREAD

**Issue by saigoud25** [mozilla/code-coverage#1483]
Icons are not loading in this website https://coverage.moz.tools/

![image](https://user-images.githubusercontent.com/42228297/177158105-ba8f461f-88c0-4118-adab-1796a0cc001d.png)

![image](https://user-images.githubusercontent.com/42228297/177158188-01d75d97-18a8-4b29-98fc-46b7896684e3.png)

**Comment by hallspaugh** [comment]
This is a duplicate of #533
