### ISSUE TITLE
249 console logs on the zero coverage report page for unknown languages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/code-coverage#1656]
### Steps to reproduce
1. Go to https://coverage.moz.tools/#view=zero
2. Open DevTools console

### Actual results
About 249 instances of:
> Unknown language for remote/cdp/targets/MainProcessTarget.sys.mjs coverage-25eab803aef85d165cbc.js:14:42744

So I wrote a little parser to see which files/extensions were unknown languages:

```js
import fs from "node:fs/promises";
import path from "node:path";

const unknownExt = new Set();

const log = await fs.readFile("./console-export-2022-11-18_10-52-43.txt", "utf-8");
let rows = log.trim()
  .split("\n")
  .filter(row => row.includes("Unknown language for "))
  .sort();

for (const row of rows) {
  const filename = row.split(" ").at(-2);
  const ext = path.extname(filename);
  unknownExt.add(ext);
  // console.log(`[${ext}] "${row.trim()}"`);
}

console.log(`[${rows.length}]`, unknownExt); // "[249] Set(2) { '.mjs', '.jsx' }"
```

#### OUTPUT

```txt
[249] Set(2) { '.mjs', '.jsx' }
```

So looks like we have 249 files of unknown language that are either *.mjs (216) or *.jsx (33).

**Comment by marco-c** [comment]
I will add these to the list of JS extensions.
