### ISSUE TITLE
New cron hook is failing because of lack of scopes

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#172]
The new cron hook from 9c8c18193d9823f8136c9047553b5e5841e62522 is failing because of lack of scopes.

**Comment by La0** [comment]
[This is fixed](https://tools.taskcluster.net/groups/I3JENZgkQW2jsyvlSMVScA/tasks/I3JENZgkQW2jsyvlSMVScA/runs/1/logs/public%2Flogs%2Flive.log).
