### ISSUE TITLE
Directly skip messages whose routingKey/schedulerId is not linked to mozilla-central or try

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#180]
We can avoid listing the task group for those, saving some resources.

**Comment by La0** [comment]
So we would only listen to `gecko-level-X` where `X` is  1,2,3 ?

**Comment by marco-c** [comment]
Yep! I think we can't directly register only for those (but maybe I'm wrong) but we can definitely skip any pulse message that does not belong to those.
