### ISSUE TITLE
404 on 563f437f24b9e12495b0f2c364538a2b8d8a0ca7, but the report is on GCP

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#257]
563f437f24b9e12495b0f2c364538a2b8d8a0ca7 and 8e8e5bb63105fd26d10f7cba6adf85a606bceaf0 are present on GCP, but they can't be loaded at https://api.coverage.moz.tools/v2/path?path=&changeset=563f437f24b9e12495b0f2c364538a2b8d8a0ca7 or https://api.coverage.moz.tools/v2/path?path=&changeset=8e8e5bb63105fd26d10f7cba6adf85a606bceaf0.

**Comment by La0** [comment]
DB server is full !

I got that in the logs:

```
2019-11-04 08:54:47.815310 code_coverage_backend.api: Failed to retrieve report: OOM command not allowed when used memory > 'maxmemory'.
```

I switched the DB plan to Premium 2, and now we have 250Mb.

We should set expirations dates on the ingested reports in the database, as they can be re-downloaded once they are expired.

**Comment by La0** [comment]
Both reports are now available :tada: 

I filed #258 to track the expiration date issue.

Also i'm manually ingesting the last few missing reports
