### ISSUE TITLE
Don't run CI on PR closure

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#262]
See also marco-c/taskcluster_yml_validator#31.

**Comment by spattk** [comment]
Hi @marco-c ,  as this a good-first-bug, can I pick this up?

**Comment by marco-c** [comment]
Sure, feel free! You have an example here: https://github.com/mozilla/microannotate/commit/6e21417744be5759f54f64cb8a2da8880317f0cd.

**Comment by spattk** [comment]
Sure, thanks.

**Comment by marco-c** [comment]
Fixed by #505.
