### ISSUE TITLE
Switch to collecting coverage data from the Linux opt build rather than the Linux debug build

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#277]
After all dependencies of https://bugzilla.mozilla.org/show_bug.cgi?id=1596275 land, we'll only have a Linux opt ccov build and not a debug build. We need to update the Taskcluster usage to use the new build.

**Comment by La0** [comment]
[First push with opt build](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&tier=1%2C2%2C3&searchStr=ccov&revision=1e1617c67238dfb685fb3d07bf1793232c4469fa)
