### ISSUE TITLE
Issue with the frontend: first file is called "ebug.c" (should be "debug.c")

### ISSUE THREAD

**Issue by sylvestre** [mozilla/code-coverage#290]
https://coverage.moz.tools/#revision=latest&path=media/mtransport/third_party/nrappkit/src/util/libekr/

**Comment by La0** [comment]
You find the weirdest bugs

**Comment by La0** [comment]
It is indeed a frontend bug, the backend sends a `debug.c` in https://api.coverage.moz.tools/v2/path?path=media/mtransport/third_party/nrappkit/src/util/libekr/
