### ISSUE TITLE
Add filtering capabilities to the API

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#3]
At the moment, the APIs are all retrieving the overall coverage.
We should add filtering capabilities so the frontend can require specific things from the backend.

Filters we should support:
- [x] Platform (Linux, Windows, Mac, etc.);
- [x] Test suite;
- [ ] Language?;
- [ ] Third-party code?

**Comment by La0** [comment]
@marco-c Are we doing the language & 3rd party filters ?

**Comment by marco-c** [comment]
These could be generated by the backend on-the-fly when requested. I'd file a separate issue for that.

**Comment by marco-c** [comment]
Opened #164.
