### ISSUE TITLE
 Switch Mercurial to Python 3

### ISSUE THREAD

**Issue by La0** [mozilla/code-coverage#332]
https://github.com/mozilla/bugbug/commit/e023dc62ea3c44cb87591c6f4753fb071428cd84 :tada:

**Comment by marco-c** [comment]
Unfortunately we need to wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1604652 :(

**Comment by marco-c** [comment]
First step has been done with https://github.com/mozilla/code-coverage/commit/c7c2672b0c81bb2b7bea0a23b46b6812884852f5.
