### ISSUE TITLE
Use tenacity in download_binary

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#392]
https://github.com/mozilla/code-coverage/blob/e621d18c259773cafc466b092396ede9ff69b566/report/firefox_code_coverage/codecoverage.py#L70

**Comment by menarulalam** [comment]
Can I work on this issue?

**Comment by marco-c** [comment]
@menarulalam sure, feel free. Anyone can work on any open issue which has no PR linked to it.

**Comment by NitishNaineni** [comment]
@marco-c  
Its my first time contributing to something but re-written the function with tenacity. Can you review and explain me the process after that?
`def download_binary(url, path, retries=5):
    """Download a binary file from an url"""
    @tenacity.retry(stop=tenacity.stop_after_attempt(retries),
                    wait=tenacity.wait_incrementing(start = 1, increment = 1),
                    reraise=True)
    def retry_function():
        try:
            artifact = requests.get(url, stream=True)
            artifact.raise_for_status()

            with open(path, "wb") as f:
                for chunk in artifact.iter_content(chunk_size=8192):
                    f.write(chunk)
        except:
            print("yo wtf")
            try:
                os.remove(path)
            except OSError:
                pass
            raise Exception(
                    "Download failed after {} retries - {}".format(retry_function.retry.statistics["attempt_number"], url)
                )
    
    retry_function()`

**Comment by NitishNaineni** [comment]
Its my first time contributing to something but re-written the function with tenacity. Can you review and explain me the process after that?

`def download_binary(url, path, retries=5):
    """Download a binary file from an url"""
    @tenacity.retry(stop=tenacity.stop_after_attempt(retries),
                    wait=tenacity.wait_incrementing(start = 1, increment = 1),
                    reraise=True)
    def retry_function():
        try:
            artifact = requests.get(url, stream=True)
            artifact.raise_for_status()

            with open(path, "wb") as f:
                for chunk in artifact.iter_content(chunk_size=8192):
                    f.write(chunk)
        except:
            print("yo wtf")
            try:
                os.remove(path)
            except OSError:
                pass
            raise Exception(
                    "Download failed after {} retries - {}".format(retry_function.retry.statistics["attempt_number"], url)
                )
    
    retry_function()`

**Comment by NitishNaineni** [comment]
@marco-c  It my first time contributing to something but i have re written the function with tenacity. Would you review and guide through the process after that?
```python 
def download_binary(url, path, retries=5):
    """Download a binary file from an url"""
    @tenacity.retry(stop=tenacity.stop_after_attempt(retries),
                    wait=tenacity.wait_incrementing(start = 1, increment = 1),
                    reraise=True)
    def retry_function():
        try:
            artifact = requests.get(url, stream=True)
            artifact.raise_for_status()

            with open(path, "wb") as f:
                for chunk in artifact.iter_content(chunk_size=8192):
                    f.write(chunk)
        except:
            print("yo wtf")
            try:
                os.remove(path)
            except OSError:
                pass
            raise Exception(
                    "Download failed after {} retries - {}".format(retry_function.retry.statistics["attempt_number"], url)
                )
    
    retry_function()
```

**Comment by marco-c** [comment]
Hello @NitishNaineni, it is hard to review in an issue, reviews should happen in pull requests. Please submit a pull request and I'll review your change ;)

**Comment by NitishNaineni** [comment]
@marco-c  sure i will do that
