### ISSUE TITLE
Zero coverage view shows files with coverage

### ISSUE THREAD

**Issue by La0** [mozilla/code-coverage#394]
No last push info either. Something is funky

**Comment by marco-c** [comment]
@La0 did you select `Show completely uncovered files only`?

**Comment by La0** [comment]
You're right, it was unchecked, as it's unchecked by default when you browse on `https://coverage.moz.tools/#view=zero`

We should probably restore it as before (i think it was enabled by default ?)

**Comment by marco-c** [comment]
Sounds good, let's open a new issue for that and keep this about the broken last push.
