### ISSUE TITLE
Remove usage of libmozevent.utils.retry

### ISSUE THREAD

**Issue by La0** [mozilla/code-coverage#416]
There is one remaining usage of `retry` in the events projects: it should be either 
1. completely removed to rely  only on Taskcluster retries,
2. or re-implemented with tenacity

**Comment by junngo** [comment]
Should It change `libmozevent.utils.retry` to tenacity decorator (i.e, `@tenacity.retry()`)?

**Comment by marco-c** [comment]
As @La0 said, either use the built-in Taskcluster maxRetries or use tenacity.
I guess the first would be preferable so we don't have to add tenacity to the requirements.

In practice, retrying is already enabled by default by the taskcluster library, so I think we can just remove the usage of retry altogether and we'll be good.
