### ISSUE TITLE
Speed up download unit tests

### ISSUE THREAD

**Issue by La0** [mozilla/code-coverage#449]
These 2 tests are taking a lot more time than all the other tests combined:

```
tests/test_taskcluster.py::test_download_artifact_forbidden PASSED       [ 98%]
tests/test_taskcluster.py::test_download_artifact_badzip PASSED          [ 99%]
```

There is certainly a timeout / retry going haywire in the unit test context (no need to retry nor wait a lot here).

**Comment by alexeicoreiba** [comment]
I am in @kohilanmohanarajan 's team. Would like to take this issue. Thanks.

**Comment by La0** [comment]
Sure, you can make a Pull Request and ask me for review !
