### ISSUE TITLE
Expire suite reports

### ISSUE THREAD

**Issue by La0** [mozilla/code-coverage#451]
We should just keep the `all:all` on the server permanently, but remove the detailed suites as they can be ingested on demand.
It would keep the DB space usage low

**Comment by marco-c** [comment]
We could set a `volatile-lru` maxmemory policy for Redis, setting an expiration only for the suite-level reports.
This way, all:all reports will be kept, and least-recently used suite-level reports will be evicted when needed.

**Comment by La0** [comment]
Dupe of #258 . Doing that now.
