### ISSUE TITLE
gtest coverage

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/code-coverage#455]
Here's a directory that should have quite good coverage from gtests - https://coverage.moz.tools/#revision=latest&path=intl%2Flocale&view=directory

and currently is shown at 0%.

It seems that gtests are not being executed for that coverage analysis?

**Comment by marco-c** [comment]
Yes, it seems gtests were not executed: https://coverage.moz.tools/#revision=latest&path=intl%2Flocale%2Ftests%2Fgtest&view=directory.

**Comment by marco-c** [comment]
It's a broader issue, tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1621342.
