### ISSUE TITLE
<link rel="icon" href="[object Module]" type="image/png"/>

### ISSUE THREAD

**Issue by Rob--W** [mozilla/code-coverage#533]
STR:

1. View the source of https://coverage.moz.tools/
2. Look fior `rel="icon"`

Expected:
- The `href` attribute should point to a URL or path.

Actual:

- It has the value `href="[object Module]"`.

Using `require(...)` here does probably not behave as expected:
https://github.com/mozilla/code-coverage/blob/2966037656f532041e855de5a667d4e918cc6a69/frontend/src/base.html#L6

**Comment by hallspaugh** [comment]
I have a PR open for this fix
https://github.com/mozilla/code-coverage/pull/1573
