### ISSUE TITLE
Stop using json-rev everywhere

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#668]
It has become superslow in the latest versions of Mercurial, as it is now returning all changes in the revision.

We can instead use json-automationrelevance or json-info.

**Comment by shubham-y** [comment]
Hi @marco-c , can you guide me on this ? I would like to work on this issue

**Comment by marco-c** [comment]
Hello @shubham-y, you'll need to change https://github.com/mozilla/code-coverage/blob/565393272f868ea3f433ab4b5615fe8c457ebaf4/backend/code_coverage_backend/hgmo.py#L20 to use json-automationrelevance or json-info (json-info is probably preferable) instead of json-rev.

1. Modify HGMO_REVISION_URL to use json-automationrelevance or json-info instead of json-rev
2. Make sure the result of the `hgmo_revision_details` function is the same before and after your change, for a given repository and revision (you can use `mozilla-central` as repository, and `0058e174c5d0a4f751398b5aefcce42adc511535` as revision). Luckily you can test it in isolation, as this function doesn't depend on other parts of the project.

**Comment by mugunthanramesh** [comment]
Is anyone taking this issue ? Can i take this and i have few doubts @marco-c i am new here please correct me if i am wrong
1. i checked json-info but it doesn't return pushid 
2. json-automationrelevance may also slow down. It information on what changesets are relevant to automated consumers given a source changeset. (from the doc)

**Comment by marco-c** [comment]
> Is anyone taking this issue ? Can i take this

Issues are taken/assigned when there is a PR linked to them.

> i checked json-info but it doesn't return pushid

OK, we can't use it then.

> json-automationrelevance may also slow down. It information on what changesets are relevant to automated consumers given a source changeset. (from the doc)

It is slower than json-info, but way faster than json-rev, so let's switch to json-automationrelevance.

**Comment by mugunthanramesh** [comment]
ok i will make a PR with json-automationrelevance.

**Comment by mugunthanramesh** [comment]
Need to update the [tests](https://github.com/mozilla/code-coverage/blob/master/backend/tests/conftest.py#L138) checks are failing

**Comment by Anupam-USP** [comment]
Hey @marco-c Is the issue still open I want to contribute?

**Comment by marco-c** [comment]
@Anupam-USP the issue is still open, there is a PR linked to it but it has probably been abandoned.
