### ISSUE TITLE
Explain heuristics used for "uncovered files" in the UI

### ISSUE THREAD

**Issue by jryans** [mozilla/code-coverage#97]
From Marco:

> For JavaScript files, the top-level code is always covered if the file is loaded, so we came up with a heuristic: a "zero coverage" file is a file which has at least one function and whose functions are all not covered.
> For C/C++ it's easier, as there's no top-level code and the code is always in functions. In this case, a "zero coverage" file is a file which has no covered lines.

It would great to put this in the UI somewhere for new users. Maybe add a "?" icon next to the uncovered files option that can show this explanation on hover.

**Comment by KohilanMohanarajan** [comment]
I'd like to take this issue.

**Comment by La0** [comment]
Go ahead, make a Pull Request and ask me for review.
